[pytest]
python_files = test_03_shop.py test_01_form.py test_02_calc.py

markers = 
    positive: Только позитивные тесты
    negative: Только негативные тесты
    positive_and_negative: Позитивные и негативные тесты
